version: "3.7"
services:
  nuxt-data:
    container_name: nuxt-data
    image: $NUXT_IMAGE_NAME_VERSION
    build:
      context: .
      dockerfile: ./docker/nuxt/Dockerfile
    volumes:
      - nuxt:/app
    command: "true"
  nuxt:
    container_name: nuxt
    image: nginx:stable-alpine
    ports:
      - 3000:80
    volumes:
      - ./docker/nuxt/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - type: volume
        source: nuxt
        target: /usr/share/nginx/html
        read_only: true
        volume:
          nocopy: true
    depends_on:
      - nuxt-data
  storybook-data:
    container_name: storybook-data
    image: $STORYBOOK_IMAGE_NAME_VERSION
    build:
      context: .
      dockerfile: ./docker/storybook/Dockerfile
    volumes:
      - storybook:/app
    command: "true"
  storybook:
    container_name: storybook
    image: nginx:stable-alpine
    ports:
      - 9000:80
    volumes:
      - type: volume
        source: storybook
        target: /usr/share/nginx/html
        read_only: true
        volume:
          nocopy: true
    depends_on:
      - storybook-data

volumes:
  nuxt:
  storybook:
